# Generated by Django 2.0.2 on 2018-03-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('dispositivo', models.CharField(max_length=25)),
                ('marca', models.CharField(blank=True, max_length=25)),
                ('modelo', models.CharField(blank=True, max_length=25)),
                ('num_serie', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de asignación: ')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario')),
            ],
        ),
    ]
